{{- if include "cw-agent.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cw-agent.fullname" . }}-api-key
  labels:
    {{- include "cw-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  api-key: {{ include "cw-agent.apiKeyValue" . | b64enc | quote }}
{{- end }}
