{{- if .Values.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cw-agent.fullname" . }}-api-key
  labels:
    {{- include "cw-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  api-key: {{ .Values.apiKey.value | b64enc | quote }}
{{- end }}